import { SearchResult } from '../components/SearchResultCard/SearchResultCard';

export const mockSearchResults: SearchResult[] = [
  {
    id: 201,
    type: 'job',
    title: 'Marketing Manager',
    company: 'BrightWave Solutions',
    companyInitials: 'BW',
    companyColor: '#2454FF',
    verified: true,
    location: 'Dayton, OH',
    workMode: 'On-site',
    employmentType: 'Full-time',
    salary: '$60K – $80K / year',
    description: "We're looking for a creative and data-driven Marketing Manager to lead our marketing initiatives and drive brand growth.",
    skills: ['Marketing Strategy', 'Digital Marketing', 'Analytics'],
    postedTime: '2h ago',
    badge: 'Featured',
    badgeColor: '#2454FF',
  },
  {
    id: 202,
    type: 'job',
    title: 'Marketing Manager',
    company: 'DigitalStream Agency',
    companyInitials: 'DS',
    companyColor: '#7B3EFF',
    verified: true,
    location: 'Dayton, OH',
    workMode: 'Hybrid',
    employmentType: 'Full-time',
    salary: '$55K – $75K / year',
    description: 'Lead integrated marketing campaigns and work with cross-functional teams to deliver results.',
    skills: ['SEO', 'Paid Ads', 'Content Strategy', 'Email Marketing'],
    postedTime: '4h ago',
    badge: 'New',
    badgeColor: '#14B87A',
  },
  {
    id: 203,
    type: 'gig',
    title: 'Marketing Strategy Consultation',
    company: 'Sarah Mitchell',
    companyInitials: 'SM',
    companyColor: '#F59E0B',
    verified: true,
    location: 'Dayton, OH',
    workMode: 'Remote',
    employmentType: 'Gig',
    price: 'From $250',
    rating: 4.9,
    reviewCount: 128,
    description: 'I will create a custom marketing strategy to grow your brand and increase conversions.',
    skills: ['Marketing Strategy', 'Branding', 'Market Research'],
    postedTime: '',
    badge: 'Top Rated',
    badgeColor: '#F59E0B',
  },
  {
    id: 204,
    type: 'business',
    title: 'Upmark Digital',
    company: 'Digital Marketing Agency',
    companyInitials: 'UP',
    companyColor: '#0B1739',
    verified: false,
    location: 'Dayton, OH',
    rating: 4.8,
    reviewCount: 56,
    openStatus: 'Open now',
    description: 'We help businesses grow through result-driven digital marketing and branding solutions.',
    skills: ['Web Design', 'SEO', 'Social Media Marketing', 'PPC'],
    postedTime: '',
  },
  {
    id: 205,
    type: 'service',
    title: 'Social Media Marketing Service',
    company: 'GrowBoost Media',
    companyInitials: 'GB',
    companyColor: '#14B87A',
    verified: false,
    location: 'Dayton, OH',
    workMode: 'Remote',
    employmentType: 'Service',
    price: 'From $150',
    description: 'Boost your brand visibility with our expert social media marketing services.',
    skills: ['Social Media', 'Content Creation', 'Management'],
    postedTime: '5h ago',
  },
  {
    id: 206,
    type: 'job',
    title: 'Senior Marketing Analyst',
    company: 'DataForce Inc.',
    companyInitials: 'DF',
    companyColor: '#EF4444',
    verified: true,
    location: 'Columbus, OH',
    workMode: 'Remote',
    employmentType: 'Full-time',
    salary: '$70K – $95K / year',
    description: 'Analyze marketing performance data and provide actionable insights to optimize campaigns across channels.',
    skills: ['Google Analytics', 'SQL', 'Tableau', 'A/B Testing'],
    postedTime: '6h ago',
    badge: 'New',
    badgeColor: '#14B87A',
  },
  {
    id: 207,
    type: 'job',
    title: 'Content Marketing Specialist',
    company: 'CreativeFlow Studios',
    companyInitials: 'CF',
    companyColor: '#7B3EFF',
    verified: false,
    location: 'Dayton, OH',
    workMode: 'On-site',
    employmentType: 'Full-time',
    salary: '$45K – $60K / year',
    description: 'Create compelling content strategies that drive engagement and establish thought leadership in our industry.',
    skills: ['Content Writing', 'SEO', 'Social Media', 'CMS'],
    postedTime: '8h ago',
  },
];

// Category counts for tabs
export const categoryCounts = {
  all: 312,
  jobs: 184,
  gigs: 56,
  businesses: 42,
  services: 18,
  events: 12,
};
