
import { Job } from '../components/JobListingGrid/JobCard';

export const mockJobs: Job[] = [
  {
    id: 1,
    title: 'Senior React Developer',
    company: 'Google',
    companyInitials: 'G',
    companyColor: '#4285F4',
    location: 'Bangalore, India',
    salary: '25–40 LPA',
    experience: '5–8 years',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    skills: ['React', 'TypeScript', 'GraphQL', 'Node.js', 'AWS'],
    description: 'Join our world-class engineering team to build scalable, high-performance web applications that serve billions of users globally.',
    postedTime: '2 hours ago',
    isFeatured: true,
    applicants: 142,
  },
  {
    id: 2,
    title: 'UI/UX Designer',
    company: 'Adobe',
    companyInitials: 'Ae',
    companyColor: '#FF0000',
    location: 'Remote',
    salary: '18–28 LPA',
    experience: '3–5 years',
    jobType: 'Full Time',
    workMode: 'Remote',
    skills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research', 'CSS'],
    description: 'Design beautiful, intuitive interfaces for our suite of creative software used by millions of professionals worldwide.',
    postedTime: '5 hours ago',
    isFeatured: true,
    applicants: 87,
  },
  {
    id: 3,
    title: 'Backend Engineer',
    company: 'Microsoft',
    companyInitials: 'M',
    companyColor: '#00A4EF',
    location: 'Hyderabad, India',
    salary: '30–45 LPA',
    experience: '4–7 years',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    skills: ['Python', 'Azure', 'Docker', 'Kubernetes', 'PostgreSQL'],
    description: 'Build and maintain robust microservices and distributed systems for Azure cloud platform serving enterprise customers.',
    postedTime: '1 day ago',
    applicants: 203,
  },
  {
    id: 4,
    title: 'Product Manager',
    company: 'Netflix',
    companyInitials: 'N',
    companyColor: '#E50914',
    location: 'Mumbai, India',
    salary: '35–55 LPA',
    experience: '5–8 years',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    skills: ['Product Strategy', 'Agile', 'Analytics', 'SQL', 'Roadmapping'],
    description: "Lead product strategy for our streaming platform's recommendation engine, driving personalization for 240M subscribers globally.",
    postedTime: '2 days ago',
    isFeatured: true,
    applicants: 312,
  },
  {
    id: 5,
    title: 'Data Scientist',
    company: 'Amazon',
    companyInitials: 'A',
    companyColor: '#FF9900',
    location: 'Chennai, India',
    salary: '28–42 LPA',
    experience: '3–6 years',
    jobType: 'Full Time',
    workMode: 'On-site',
    skills: ['Python', 'TensorFlow', 'Spark', 'AWS SageMaker', 'Statistics'],
    description: 'Develop ML models for demand forecasting, pricing optimization, and supply chain automation at massive scale.',
    postedTime: '3 days ago',
    applicants: 178,
  },
  {
    id: 6,
    title: 'DevOps Engineer',
    company: 'Stripe',
    companyInitials: 'St',
    companyColor: '#7B3EFF',
    location: 'Remote',
    salary: '22–35 LPA',
    experience: '3–5 years',
    jobType: 'Full Time',
    workMode: 'Remote',
    skills: ['Kubernetes', 'Terraform', 'CI/CD', 'AWS', 'Go'],
    description: "Architect and maintain infrastructure for one of the world's fastest-growing payment platforms processing trillions in volume.",
    postedTime: '4 days ago',
    isUrgent: true,
    applicants: 95,
  },
  {
    id: 7,
    title: 'iOS Developer',
    company: 'Spotify',
    companyInitials: 'S',
    companyColor: '#1DB954',
    location: 'Pune, India',
    salary: '20–32 LPA',
    experience: '3–5 years',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    skills: ['Swift', 'Objective-C', 'Xcode', 'Core Data', 'REST APIs'],
    description: 'Build features for our iOS app used by 600M+ users to discover and stream music, podcasts, and audiobooks.',
    postedTime: '5 days ago',
    applicants: 134,
  },
  {
    id: 8,
    title: 'Full Stack Developer',
    company: 'Figma',
    companyInitials: 'F',
    companyColor: '#F24E1E',
    location: 'Remote',
    salary: '18–30 LPA',
    experience: '2–4 years',
    jobType: 'Full Time',
    workMode: 'Remote',
    skills: ['React', 'Node.js', 'WebSocket', 'TypeScript', 'MongoDB'],
    description: 'Work on our collaborative design platform, building real-time features that enable teams to create exceptional products.',
    postedTime: '6 days ago',
    applicants: 267,
  },
  {
    id: 9,
    title: 'Marketing Manager',
    company: 'Google',
    companyInitials: 'G',
    companyColor: '#4285F4',
    location: 'Delhi, India',
    salary: '15–25 LPA',
    experience: '4–6 years',
    jobType: 'Full Time',
    workMode: 'Hybrid',
    skills: ['SEO', 'Google Analytics', 'Content Strategy', 'Paid Ads', 'CRM'],
    description: 'Drive growth marketing strategies for Google Workspace, identifying opportunities to expand our enterprise customer base.',
    postedTime: '1 week ago',
    applicants: 421,
  },
  {
    id: 10,
    title: 'Security Engineer',
    company: 'Microsoft',
    companyInitials: 'M',
    companyColor: '#00A4EF',
    location: 'Bangalore, India',
    salary: '35–50 LPA',
    experience: '6–9 years',
    jobType: 'Full Time',
    workMode: 'On-site',
    skills: ['SIEM', 'Penetration Testing', 'Azure Security', 'Zero Trust', 'Python'],
    description: "Protect Microsoft's global cloud infrastructure by identifying vulnerabilities and building security-first solutions.",
    postedTime: '1 week ago',
    isUrgent: true,
    applicants: 67,
  },
  {
    id: 11,
    title: 'Content Writer',
    company: 'Spotify',
    companyInitials: 'S',
    companyColor: '#1DB954',
    location: 'Remote',
    salary: '8–15 LPA',
    experience: 'Entry Level',
    jobType: 'Contract',
    workMode: 'Remote',
    skills: ['Content Strategy', 'SEO Writing', 'Copywriting', 'Research', 'Adobe InDesign'],
    description: "Create compelling stories and editorial content for Spotify's blog, social media, and in-app communications.",
    postedTime: '2 weeks ago',
    applicants: 589,
  },
  {
    id: 12,
    title: 'QA Engineer',
    company: 'Amazon',
    companyInitials: 'A',
    companyColor: '#FF9900',
    location: 'Hyderabad, India',
    salary: '12–20 LPA',
    experience: '2–4 years',
    jobType: 'Full Time',
    workMode: 'On-site',
    skills: ['Selenium', 'Jest', 'Cypress', 'Python', 'API Testing'],
    description: "Ensure the quality and reliability of Amazon's e-commerce platform through automated and manual testing at scale.",
    postedTime: '2 weeks ago',
    applicants: 156,
  },
];
